fix(core): attemp to fix the install path

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,9 +2,9 @@
 
 set -euo pipefail
 
-[ -z "${ASDF_INSTALL_TYPE+x}" ] && echo "ASDF_INSTALL_TYPE is required" && exit 1
-[ -z "${ASDF_INSTALL_VERSION+x}" ] && echo "ASDF_INSTALL_VERSION is required" && exit 1
-[ -z "${ASDF_INSTALL_PATH+x}" ] && echo "ASDF_INSTALL_PATH is required" && exit 1
+# [ -z "${ASDF_INSTALL_TYPE+x}" ] && echo "ASDF_INSTALL_TYPE is required" && exit 1
+# [ -z "${ASDF_INSTALL_VERSION+x}" ] && echo "ASDF_INSTALL_VERSION is required" && exit 1
+# [ -z "${ASDF_INSTALL_PATH+x}" ] && echo "ASDF_INSTALL_PATH is required" && exit 1
 
 install() {
   local install_type=$1
@@ -16,11 +16,9 @@ install() {
   local download_url="https://github.com/npryce/adr-tools/archive/${version}.tar.gz"
 
   echo "-- Downloading adr-tools from ${download_url}"
-  curl -sL "$download_url" -o adr.tar
-  (
-    tar zxf adr.tar -C $install_path --strip-components=1 || exit 1
-  )
-  rm adr.tar
+  curl -sL "$download_url" | tar xz
+  mv adr-tools-${version}/src $install_path/bin
+  rm -rf adr-tools-${version}
 }
 
 install "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH" 
